-- 创建用户表
CREATE TABLE SYS_USER (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    USERNAME VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(128) NOT NULL,
    SALT VARCHAR(32) NOT NULL,
    STATUS TINYINT DEFAULT 0 NOT NULL,
    REAL_NAME VARCHAR(20),
    HEAD_URL VARCHAR(128),
    EMAIL VARCHAR(255),
    MOBILE VARCHAR(255),
    POSITION VARCHAR(16),
    DEL_FLG TINYINT DEFAULT 0 NOT NULL,
    CREATE_ID BIGINT NOT NULL,
    UPDATE_ID BIGINT,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REMARK VARCHAR(255)
);

-- 添加注释
COMMENT ON TABLE SYS_USER IS '系统--用户表';

COMMENT ON COLUMN SYS_USER.USERNAME IS '登录名';
COMMENT ON COLUMN SYS_USER.PASSWORD IS '登录密码(用户输入明文 前端计算MD5 后端加盐)';
COMMENT ON COLUMN SYS_USER.SALT IS '盐值';
COMMENT ON COLUMN SYS_USER.STATUS IS '账号状态(0:默认正常,1:禁用)';
COMMENT ON COLUMN SYS_USER.REAL_NAME IS '真实姓名';
COMMENT ON COLUMN SYS_USER.HEAD_URL IS '头像URL minio相对路径';
COMMENT ON COLUMN SYS_USER.EMAIL IS '邮箱';
COMMENT ON COLUMN SYS_USER.MOBILE IS '手机号';
COMMENT ON COLUMN SYS_USER.POSITION IS '职位';
COMMENT ON COLUMN SYS_USER.DEL_FLG IS '是否删除 0正常 1删除';
COMMENT ON COLUMN SYS_USER.CREATE_ID IS '创建人id';
COMMENT ON COLUMN SYS_USER.UPDATE_ID IS '更新人id';
COMMENT ON COLUMN SYS_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYS_USER.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYS_USER.REMARK IS '备注';